name: Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Init
        run: terraform init

      - name: Plan
        env:
          TF_VAR_github_deploy_key: ${{ secrets.DEPLOY_KEY }}
          TF_VAR_db_host: ${{ secrets.TF_VAR_DB_HOST }}
          TF_VAR_db_name: ${{ secrets.TF_VAR_DB_NAME }}
          TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_env: ${{ secrets.TF_VAR_ENV }}
          TF_VAR_app_name: ${{ secrets.TF_VAR_APP_NAME }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_ec2_name: ${{ secrets.TF_VAR_EC2_NAME }}
          TF_VAR_ec2_instance_type: ${{ secrets.TF_VAR_EC2_INSTANCE_TYPE }}
          TF_VAR_ec2_ami: ${{ secrets.TF_VAR_EC2_AMI }}
        run: terraform plan

      - name: Apply
        env:
          TF_VAR_github_deploy_key: ${{ secrets.DEPLOY_KEY }}
          TF_VAR_db_host: ${{ secrets.TF_VAR_DB_HOST }}
          TF_VAR_db_name: ${{ secrets.TF_VAR_DB_NAME }}
          TF_VAR_db_username: ${{ secrets.TF_VAR_DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_env: ${{ secrets.TF_VAR_ENV }}
          TF_VAR_app_name: ${{ secrets.TF_VAR_APP_NAME }}
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_ec2_name: ${{ secrets.TF_VAR_EC2_NAME }}
          TF_VAR_ec2_instance_type: ${{ secrets.TF_VAR_EC2_INSTANCE_TYPE }}
          TF_VAR_ec2_ami: ${{ secrets.TF_VAR_EC2_AMI }}
        run: terraform apply -auto-approve